name: syncJob
on:
  schedule:
    - cron: '0 */18 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://wuxiaapi-stg.herokuapp.com/syncJob?key=${{ secrets.SYNCJOBKEY }}'
